### ISSUE TITLE
Usage with srcset

### ISSUE THREAD

**Issue by FistMeNaruto** [reallifedigital/nuxt-image-loader-module#13]
Hi!

I was wondering if there is planned support for `srcset` property on `nuxt-image` component? It would be great if I could pass srcset prop as an array of styles i.e. `srcset=["small", "medium", "large"]` and get the urls and sizes generated on img element as `srcset="img--small.jpg 642w, img--medium.jpg 1284w, img--large.jpg 1926w"`, I'm just not sure if it is possible to generate multiple images.

Nice and clean coding style, by the way!

**Comment by barryrld** [comment]
Hi @FistMeNaruto 

Thanks for the feedback. `srcset` support would be a nice addition. I'm current a bit stacked with client work at the moment, but I'll certainly add this to the roadmap although there's no official log outside of this issue queue.

I'd like to have `srcset` presets defined as separate config items in the module config to achieve what you outlined as you use case. There probably ought to be some validation on the config to check for potential errors. Also, there should be a consideration for the sizes attribute which could be part of the preset definition.

Let's leave this open and when I have some time I'll see if I can get this done along with tests. If you don't hear back after a few weeks, feel free to bump!

Thanks,

Barry

**Comment by barryrld** [comment]
Hi @FistMeNaruto 

Please check out v1.4.0 and the new README relating to responsive images. If you have any questions please open another ticket.

The CI server is having issues at the moment, possibly with the latest version of nuxt broken upstream, I'm not sure. All tests pass on my machine running nuxt 2.2.0.

I hope this helps! :smile:

Barry
